REWARD_COEF = {
    "PERTURBATION" : 1,
    "LABEL" : 1,
    "MIN_STEPS" : 1
}
MAX_PERTURBATION = 4.0
NUM_CLASSES = 10
NUM_OF_CLUSTERS = 2
MAX_STEPS = 200
MIN_STEPS_REWARD_TH0 = 5
MIN_STEPS_REWARD_TH1 = 10
INITIAL_STEP_SIZE = 0.1

ACTIONS = ["CLOSET_CLUSTER", "FARTHEST_CLUSTER", "ORIGINAL_IMAGE", "DECREASE_STEP"] #Todo: implement normal_dist
# ACTIONS = ["CLOSET_CLUSTER", "FARTHEST_CLUSTER", "ORIGINAL_IMAGE", "NORMAL_DIST_RANDOM"]
# ACTIONS = {'left': 0, 'stop': 1, 'right': 2}
